2018-03-13 22:25:56,594 - ERROR - spider.py[:143] - (pymysql.err.InternalError) (1292, "Incorrect datetime value: '计划到达时间' for column 'ArriveTime' at row 1") [SQL: 'UPDATE user SET `ArriveTime`=%(ArriveTime)s WHERE user.`CarId` = %(user_CarId)s'] [parameters: {'ArriveTime': '计划到达时间', 'user_CarId': '浙APY123'}] (Background on this error at: http://sqlalche.me/e/2j85)
2018-03-13 22:29:30,737 - ERROR - spider.py[:145] - (pymysql.err.InternalError) (1292, "Incorrect datetime value: '计划到达时间' for column 'ArriveTime' at row 1") [SQL: 'UPDATE user SET `ArriveTime`=%(ArriveTime)s WHERE user.`CarId` = %(user_CarId)s'] [parameters: {'ArriveTime': '计划到达时间', 'user_CarId': '浙APY123'}] (Background on this error at: http://sqlalche.me/e/2j85)
